# Generated by Django 2.1.5 on 2019-01-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190123_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='humidity',
            name='change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='humidity',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='humidity',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
